apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: social-media-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - service-discovery.yaml
  - api-gateway.yaml
  - user-service.yaml
  - post-service.yaml
  - notification-service.yaml
  - chat-service.yaml
  - media-service.yaml
  - analytics-service.yaml
  - frontend.yaml
  - ingress.yaml
